---1 TABLA SUCURSAL
CREATE TABLE SUCURSAL (
ID_SUCURSAL NUMBER NOT NULL PRIMARY KEY,
DIRECCION VARCHAR2 (80),   
CONTACTO NUMBER (10)
);

---2 TABLA VENDEDOR
CREATE TABLE VENDEDOR (
ID_VENDEDOR NUMBER NOT NULL PRIMARY KEY,
FK_ID_SUCURSAL NUMBER,
NOMBRES VARCHAR2 (60),
APELLIDOS VARCHAR2(60) ,
DIRECCION VARCHAR2(80),
FECHA_NACIMIENTO DATE,
FECHA_INGRESO DATE,
JORNADA_LABORAL VARCHAR2 (40),
AÑOS_LABORAL VARCHAR2 (40),
ESTADO VARCHAR2(60) CHECK(ESTADO='ACTIVO' OR ESTADO='INACTIVO'),
CONSTRAINT VENDEDOR_SUCURSAL FOREIGN KEY (FK_ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL)
);

---3 TABLA PAGOS AL VENDEDOR
CREATE TABLE PAGOS (
ID_PAGOS NUMBER NOT NULL PRIMARY KEY,
FK_ID_VENDEDOR NUMBER,
HORAS_LABORADAS NUMBER,
HORAS_EXTRAS NUMBER,
CONSTRAINT VENDEDOR_PAGOS FOREIGN KEY (FK_ID_VENDEDOR) REFERENCES VENDEDOR (ID_VENDEDOR)
);

---4 TABLA DESCUENTO
CREATE TABLE DESCUENTO (
ID_DESCUENTO NUMBER NOT NULL PRIMARY KEY,
FK_ID_SUCURSAL NUMBER,
INICIO_DESCUENTO DATE,
FIN_DESCUENTO DATE, --ERA HORAS_EXTRA
CONSTRAINT DESCUENTO_SUCURSAL FOREIGN KEY (FK_ID_SUCURSAL) REFERENCES SUCURSAL (ID_SUCURSAL)
);

---5 TABLA PRODUCTOS
CREATE TABLE PRODUCTOS (
ID_PRODUCTO NUMBER NOT NULL PRIMARY KEY,
NOMBRE VARCHAR (30), 
STOCK NUMBER,
COSTO NUMBER,
FECHA_VENCIMIENTO DATE,
FECHA_ELABORACION DATE,
EFECTO VARCHAR2 (100)
);

-- 6 TABLA COMPUESTOS 
CREATE TABLE COMPUESTOS (
ID_COMPUESTO NUMBER NOT NULL PRIMARY KEY,
NOMBRE VARCHAR2 (60)
);

-- 7 TABLA LINE_PRODUCTO_COMPUESTO_DESCUENTO_LINE
CREATE TABLE PRODUCTO_COMPUESTO_DESCUENTO (
FK_ID_PRODUCTO NUMBER, 
FK_ID_COMPUESTO NUMBER ,
FK_ID_DESCUENTO NUMBER,
CONSTRAINT LINE_PRODUCTO FOREIGN KEY (FK_ID_PRODUCTO) REFERENCES PRODUCTOS (ID_PRODUCTO),
CONSTRAINT LINE_COMPUESTO FOREIGN KEY (FK_ID_COMPUESTO) REFERENCES COMPUESTOS (ID_COMPUESTO),
CONSTRAINT LINE_DESCUENTO FOREIGN KEY (FK_ID_DESCUENTO) REFERENCES DESCUENTO (ID_DESCUENTO)
);

-- 8 TABLA PROVEEDOR
CREATE TABLE PROVEEDOR (
ID_PROVEEDOR NUMBER NOT NULL PRIMARY KEY,
NOMBRE VARCHAR2 (60),
APELLIDOS VARCHAR2 (60),
DIRECCION VARCHAR2(80),
TELEFONO NUMBER(10)
);

-- 9 TABLA PROVEERDOR_PRODUCTO_LINE 
CREATE TABLE PROVEERDOR_PRODUCTO_LINE (
FK_ID_PROVEEDOR NUMBER,
FK_ID_PRODUCTO NUMBER,
CONSTRAINT PROVEEDOR_LINE FOREIGN KEY (FK_ID_PROVEEDOR) REFERENCES PROVEEDOR (ID_PROVEEDOR),
CONSTRAINT PRODUCTO_LINE FOREIGN KEY (FK_ID_PRODUCTO) REFERENCES PRODUCTOS (ID_PRODUCTO)
);

--10 TABLA CLIENTE
CREATE TABLE CLIENTE (
CEDULDA VARCHAR2(12) NOT NULL PRIMARY KEY,
NOMBRES VARCHAR2 (60),
APELLIDO_PATERNO VARCHAR2 (60),
APELLIDO_MATERNO VARCHAR2 (60),
DIRECCION VARCHAR2(80),
TELEFONO NUMBER(10)
);

--11 TABLA RECETA
CREATE TABLE RECETA (
ID_RECETA NUMBER NOT NULL PRIMARY KEY,
FK_CEDULDA VARCHAR2(12),
PRESCRIPCION VARCHAR(50) CHECK(PRESCRIPCION='APROBADO' OR PRESCRIPCION='DENEGADO'),
CONSTRAINT FK_RECETA_CLIENTE FOREIGN KEY (FK_CEDULDA) REFERENCES CLIENTE (CEDULDA)
);

--12 TABLA FACTURA_PRODUCTO_VENDEDOR_LINE
CREATE TABLE FACTURA_PRODUCTO_VENDEDOR_LINE (
FK_ID_RECETA NUMBER,
FK_ID_PRODUCTO NUMBER,
FK_ID_VENDEDOR NUMBER, 
CONSTRAINT FK_RECETA FOREIGN KEY (FK_ID_RECETA) REFERENCES RECETA (ID_RECETA),
CONSTRAINT FK_PRODUCTO FOREIGN KEY (FK_ID_PRODUCTO) REFERENCES PRODUCTOS (ID_PRODUCTO),
CONSTRAINT FK_VENDEDOR FOREIGN KEY (FK_ID_VENDEDOR) REFERENCES VENDEDOR (ID_VENDEDOR)
);

--13 TABLA SUCURSAL_PRODUCTO_LINE
CREATE TABLE SUCURSAL_PRODUCTO_LINE (
FK_ID_SUCURSAL NUMBER,
FK_ID_PRODUCTO NUMBER,
CONSTRAINT FK_SUCURSAL_FACTURA_LINE FOREIGN KEY (FK_ID_SUCURSAL) REFERENCES SUCURSAL (ID_SUCURSAL),
CONSTRAINT FK_PRODUCTO_FACTURA_LINE FOREIGN KEY (FK_ID_PRODUCTO) REFERENCES PRODUCTOS (ID_PRODUCTO)
);
